import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { createServer } from "node:http";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { build } from "esbuild";

const root = path.resolve(import.meta.dirname, "..");
const artifacts = path.join(root, "src-tauri/target/playlist-browser");
await mkdir(artifacts, { recursive: true });
const bundle = await build({ absWorkingDir: root, entryPoints: ["tests/playlist-harness.tsx"], bundle: true, write: false, outdir: artifacts, jsx: "automatic", loader: { ".png": "dataurl" }, define: { "process.env.NODE_ENV": '"development"' } });
const assets = new Map(bundle.outputFiles.map((file) => [path.basename(file.path), file.contents]));
const html = '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/playlist-harness.css"></head><body><div id="root"></div><script src="/playlist-harness.js"></script></body></html>';
const server = createServer((req, res) => { const name = req.url.slice(1); res.setHeader("Content-Type", name.endsWith(".js") ? "text/javascript" : name.endsWith(".css") ? "text/css" : "text/html"); res.end(assets.get(name) ?? html); });
server.listen(0, "127.0.0.1"); await once(server, "listening");
const profile = path.join(artifacts, `profile-${Date.now()}`);
const child = spawn(process.env.DOWNLOADER_TEST_BROWSER || "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe", ["--headless=new", "--disable-gpu", "--no-first-run", "--no-default-browser-check", "--remote-debugging-port=0", `--user-data-dir=${profile}`, "about:blank"], { windowsHide: true, stdio: "ignore" });
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
let socket;
const errors = [];
try {
  let port;
  for (let attempt = 0; attempt < 150; attempt++) { try { port = (await readFile(path.join(profile, "DevToolsActivePort"), "utf8")).split("\n")[0]; break; } catch { await delay(100); } }
  assert.ok(port, "Browser exposes its debugging port");
  const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  socket = new WebSocket(targets.find((target) => target.type === "page").webSocketDebuggerUrl); await once(socket, "open");
  let id = 0; const pending = new Map();
  socket.addEventListener("message", ({ data }) => { const message = JSON.parse(data); if (message.method === "Runtime.exceptionThrown") errors.push(message.params.exceptionDetails.text); if (pending.has(message.id)) { const { resolve, reject, timer } = pending.get(message.id); clearTimeout(timer); pending.delete(message.id); message.error ? reject(new Error(message.error.message)) : resolve(message.result); } });
  const send = (method, params = {}) => new Promise((resolve, reject) => { const messageId = ++id; const timer = setTimeout(() => reject(new Error(`Timed out: ${method}`)), 15000); pending.set(messageId, { resolve, reject, timer }); socket.send(JSON.stringify({ id: messageId, method, params })); });
  const evaluate = async (expression) => { const result = await send("Runtime.evaluate", { expression, returnByValue: true, awaitPromise: true }); if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description || expression); return result.result.value; };
  const until = async (expression) => { for (let attempt = 0; attempt < 100; attempt++) { if (await evaluate(expression)) return; await delay(50); } throw new Error(`Condition failed: ${expression}`); };
  const click = (selector) => evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const mouseSide = async (button) => {
    await send('Input.dispatchMouseEvent', { type: 'mousePressed', button, buttons: button === 'back' ? 8 : 16, x: 600, y: 60, clickCount: 1 });
    await send('Input.dispatchMouseEvent', { type: 'mouseReleased', button, buttons: 0, x: 600, y: 60, clickCount: 1 });
  };
  const input = (selector, value) => evaluate(`(() => { const field = document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(field.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, 'value').set.call(field, ${JSON.stringify(value)}); field.dispatchEvent(new Event('input', {bubbles:true})); })()`);
  const size = async (width, height) => { await send("Emulation.setDeviceMetricsOverride", { width, height, deviceScaleFactor: 1, mobile: false }); await delay(150); };
  const shot = async (name) => { await delay(200); const result = await send("Page.captureScreenshot", { format: "png" }); await writeFile(path.join(artifacts, name), Buffer.from(result.data, "base64")); };
  const noOverflow = async () => assert.deepEqual(await evaluate(`['.mainPane','.contentArea','.playlistCollectionToolbar','.playerBar'].filter(selector => { const el=document.querySelector(selector); return el && el.scrollWidth > el.clientWidth+1; })`), [], "Main surfaces must fit their width");
  const checkPlayer = async () => assert.equal(await evaluate(`(() => { const player=document.querySelector('.playerBar').getBoundingClientRect();return ['.playButton','.seekRow input','.volume input','.queueButton'].every(selector=>{const el=document.querySelector('.playerBar '+selector),r=el.getBoundingClientRect();return r.width>0 && r.height>0 && r.left>=player.left && r.right<=player.right+1 && r.top>=player.top && r.bottom<=player.bottom+1;});})()`), true, "Playback, seek, volume and queue remain visible inside the player");
  const checkRows = async () => {
    await until("document.querySelectorAll('.trackRow').length > 4");
    assert.ok(await evaluate("document.querySelector('.virtualScroller').clientHeight") > 120, "Song list uses available height");
    assert.equal(await evaluate(`(() => { const row=document.querySelector('.trackRow'), menu=row.querySelector('.rowMoreButton'), title=row.querySelector('.titleCell strong'), subtitle=row.querySelector('.trackSubtitle'), r=row.getBoundingClientRect(), m=menu.getBoundingClientRect(); return m.right <= r.right + 1 && m.left >= r.left && title.getBoundingClientRect().bottom <= r.bottom && subtitle.getBoundingClientRect().bottom <= r.bottom; })()`), true, "Title, subtitle and menu stay inside each row");
  };
  await send("Runtime.enable"); await send("Page.enable"); await size(1280, 900);
  await send("Page.navigate", { url: `http://127.0.0.1:${server.address().port}` });
  await until("document.querySelectorAll('.playlistCard').length === 8");
  assert.equal(await evaluate("!!document.querySelector('.miniPlayerButton')"), false, 'Pop-up mini player is removed');
  await shot("collections-desktop.png"); await noOverflow();
  await click('[aria-label="Edit After hours"]');
  await until("!!document.querySelector('.playlistEditorForm')");
  await input('.playlistEditorFields input', 'Midnight / memories');
  await input('.playlistEditorFields textarea', 'The city is asleep. This playlist isn’t.');
  await click('[aria-label="Use #b1a0dc for playlist color"]');
  await evaluate(`playlistTest.imageResult = (() => { const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=500;const ctx=canvas.getContext('2d');const g=ctx.createLinearGradient(0,0,1200,500);g.addColorStop(0,'#254641');g.addColorStop(.5,'#9b7bb7');g.addColorStop(1,'#d98e79');ctx.fillStyle=g;ctx.fillRect(0,0,1200,500);ctx.fillStyle='#ffffff20';ctx.beginPath();ctx.arc(880,210,160,0,Math.PI*2);ctx.fill();return canvas.toDataURL();})()`);
  await click('.playlistImageActions button');
  await until("!!document.querySelector('.playlistEditorPreview .playlistArtwork img')");
  await evaluate("Array.from(document.querySelectorAll('.playlistImageActions button')).find(b=>b.textContent.includes('Add banner')).click()");
  await until("!!document.querySelector('.playlistPositionControl')");
  await input('.playlistPositionControl input', '72');
  await shot("playlist-editor.png");
  await evaluate("playlistTest.failSave = true"); await click('.playlistEditorForm button[type=submit]');
  await until("document.querySelector('.playlistEditorForm [role=alert]')?.textContent.includes('Storage unavailable')");
  assert.equal(await evaluate("localStorage.getItem('playlistAppearances.v1')"), null, "Failed save preserves previous data");
  await evaluate("playlistTest.failSave = false"); await click('.playlistEditorForm button[type=submit]');
  await until("!document.querySelector('.playlistEditorForm')");
  await evaluate("Array.from(document.querySelectorAll('.playlistCard')).find(b=>b.querySelector('strong').textContent === 'Midnight / memories').click()"); await until("!!document.querySelector('.playlistHero')");
  assert.equal(await evaluate("document.querySelector('.playlistHero h2').textContent"), 'Midnight / memories');
  await click('.playlistPlayButton');
  await until("playlistTest.snapshot().playing && playlistTest.snapshot().playlistKey === '1:after hours'");
  await mouseSide('back');
  await until("!!document.querySelector('.activePlaylist .playlistPlayingStatus')");
  assert.match(await evaluate("document.querySelector('.playlistPlayingStatus').textContent"), /^Playing/);
  await click('[aria-label="Pause Midnight / memories"]');
  await until("document.querySelector('.playlistPlayingStatus').textContent.startsWith('Paused')");
  await click('[aria-label="Resume Midnight / memories"]');
  await until("document.querySelector('.playlistPlayingStatus').textContent.startsWith('Playing')");
  await evaluate("playlistTest.next()");
  await until("document.querySelector('.playlistPlayingStatus').textContent.includes('Weightless')");
  await mouseSide('forward');
  await until("!!document.querySelector('.playlistHero')");
  await checkRows(); await shot("playlist-detail.png");
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.playlistBanner img')).objectPosition"), '50% 72%');
  assert.equal(await evaluate("playlistTest.folders[0].path"), 'C:\\Music\\After hours', "Editing display name never changes music paths");
  await click('.playlistEditButton'); await until("!!document.querySelector('.playlistEditorForm')");
  await evaluate("window.dispatchEvent(new MouseEvent('auxclick',{button:3,bubbles:true,cancelable:true}))");
  assert.equal(await evaluate("!!document.querySelector('.playlistHero')"), true, 'Side buttons cannot navigate behind an open editor');
  await input('.playlistEditorFields input', 'Discard this');
  await evaluate("window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  await until("!document.querySelector('.playlistEditorForm')");
  assert.equal(await evaluate("document.querySelector('.playlistHero h2').textContent"), 'Midnight / memories');
  for (const [width,height] of [[960,640],[640,620],[390,844]]) { await size(width,height); await noOverflow(); await checkRows(); await shot(`playlist-${width}.png`); }
  await size(624, 481); await noOverflow(); await checkPlayer(); await shot('playlist-smallest-window.png');
  assert.ok(await evaluate(`(() => { const list=document.querySelector('.virtualScroller').getBoundingClientRect(), content=document.querySelector('.contentArea').getBoundingClientRect(); return Math.min(list.bottom,content.bottom)-Math.max(list.top,content.top); })()`) >= 100, 'Smallest desktop window initially shows songs below the playlist header');
  const wheelPoint = await evaluate("(() => { const r=document.querySelector('.playlistDetailView').getBoundingClientRect();return {x:r.left+r.width/2,y:r.bottom-25};})()");
  await send('Input.dispatchMouseEvent', {type:'mouseWheel',...wheelPoint,deltaX:0,deltaY:650});
  await until("document.querySelector('.playlistDetailView').scrollTop > 500");
  assert.equal(await evaluate("document.querySelector('.virtualScroller').scrollTop"), 0, 'Song rows have no separate scrollbar');
  assert.equal(await evaluate("document.querySelector('.playlistHero').getBoundingClientRect().bottom < document.querySelector('.playlistDetailView').getBoundingClientRect().top"), true, 'Scrolling songs moves the whole header out of view');
  await shot('playlist-whole-page-scroll.png');
  await evaluate("document.querySelector('.playlistDetailView').scrollTop = 100000");
  await until("!!document.querySelector('.trackRow[aria-rowindex=\"61\"]')");
  assert.ok(await evaluate("document.querySelectorAll('.trackRow').length") < 30, 'Whole-page scrolling still virtualizes the song list');
  await evaluate("document.querySelector('.playlistDetailView').scrollTop = 0");
  await size(1280,900); await evaluate("document.documentElement.dataset.theme='light'"); await shot('playlist-light.png');
  await send('Page.reload'); await until("!!document.querySelector('[aria-label=\"Edit Midnight / memories\"]')");
  await input('.playlistSearch input', 'Midnight'); await until("document.querySelectorAll('.playlistCard').length === 1");
  await evaluate("playlistTest.openPicker()"); await until("!!document.querySelector('.playlistPickerSearch input')");
  await input('.playlistPickerSearch input', 'Midnight'); await until("document.querySelectorAll('.playlistPickerOption').length === 1");
  assert.equal(await evaluate("document.querySelector('.playlistPickerOption strong').textContent"), 'Midnight / memories');
  await click('[aria-label="Close playlist picker"]');
  await click('[aria-label="Songs"]'); await until("!!document.querySelector('.songStack')");
  await evaluate("window.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',altKey:true,cancelable:true}))");
  await until("!!document.querySelector('.userPlaylistsView')");
  await evaluate("window.dispatchEvent(new KeyboardEvent('keydown',{key:'BrowserForward',cancelable:true}))");
  await until("!!document.querySelector('.songStack')");
  for (const [width,height] of [[1280,900],[960,640],[640,620],[390,844]]) { await size(width,height); await noOverflow(); await checkRows(); await checkPlayer(); await shot(`songs-${width}.png`); }
  await evaluate("document.documentElement.dataset.density='compact';document.documentElement.style.setProperty('--font-scale','1.2')");
  await checkRows();
  await size(1280, 900);
  await send('Page.navigate', { url: `http://127.0.0.1:${server.address().port}/?full-app` });
  await until("document.querySelectorAll('.playlistCard').length === 8");
  await until("playlistTest.snapshot().playlistKey === '1:after hours'");
  assert.equal(await evaluate("playlistTest.snapshot().playing"), false, 'Restored playlist sessions stay paused');
  await click('[aria-label="Play A little louder"]');
  await until("playlistTest.commands.includes('mark_track_played')");
  await delay(250);
  assert.equal(await evaluate("playlistTest.commands.filter(c=>c==='list_tracks').length"), 1, 'Playing a song does not refetch the entire library');
  assert.equal(await evaluate("playlistTest.commands.filter(c=>c==='list_playlist_folders').length"), 1, 'Playing a song does not rescan playlist folders');
  await evaluate("playlistTest.sessionWrites = 0; playlistTest.volumeBurst()");
  assert.equal(await evaluate("playlistTest.sessionWrites"), 0, 'Volume dragging does not synchronously serialize the queue');
  await delay(800);
  assert.equal(await evaluate("playlistTest.sessionWrites"), 1, 'Volume changes save once after dragging settles');
  await click('[aria-label="Folders"]');
  await until("!!document.querySelector('.folderRootCard') || !!document.querySelector('.folderBrowser')");
  await evaluate("playlistTest.navigation.navigate({...playlistTest.navigation.current(), folder:{rootId:1,relativePath:'',path:'C:\\\\Music',rootName:'Music'}})");
  await until("playlistTest.commands.includes('list_library_folder')");
  await evaluate("playlistTest.navigation.navigate({...playlistTest.navigation.current(), folder:{rootId:1,relativePath:'After hours',path:'C:\\\\Music\\\\After hours',rootName:'Music'}})");
  await evaluate("window.dispatchEvent(new MouseEvent('auxclick',{button:3,bubbles:true,cancelable:true}))");
  assert.equal(await evaluate("playlistTest.navigation.current().folder.relativePath"), '', 'Mouse back traverses folder locations');
  await click('[aria-label="Songs"]');
  await click('[aria-label="Go back"]');
  await until("!!document.querySelector('.folderBrowser')");
  await click('[aria-label="Go forward"]');
  await until("!!document.querySelector('.songStack')");
  await click('.trackRow .rowPlay');
  await until("playlistTest.snapshot().playlistKey === null");
  await shot('app-navigation.png');
  assert.deepEqual(errors, [], "No unhandled errors");
  console.log('Playlist checks passed: customization, persistence, whole-page scrolling, virtualization, playing/paused indicators, popup removal, mouse/keyboard navigation, and no full-library or folder reload on playback.');
  console.log(`Screenshots: ${artifacts}`);
  await send('Browser.close');
} finally { socket?.close(); child.kill(); server.close(); }
